package News.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import News.db.Journalism;

import News.db.JournalismDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig journalismDaoConfig;

    private final JournalismDao journalismDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        journalismDaoConfig = daoConfigMap.get(JournalismDao.class).clone();
        journalismDaoConfig.initIdentityScope(type);

        journalismDao = new JournalismDao(journalismDaoConfig, this);

        registerDao(Journalism.class, journalismDao);
    }
    
    public void clear() {
        journalismDaoConfig.clearIdentityScope();
    }

    public JournalismDao getJournalismDao() {
        return journalismDao;
    }

}
