package News.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "JOURNALISM".
 */
@Entity
public class Journalism {

    @Id
    private Long id;
    private String title;

    @Generated
    public Journalism() {
    }

    public Journalism(Long id) {
        this.id = id;
    }

    @Generated
    public Journalism(Long id, String title) {
        this.id = id;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
